service: user

provider:
  name: aws
  runtime: python3.6

functions:
  preSignUp:
    handler: preSignUp.handler
    description: Triggered directly before sign up email is sent to new user.
    events:
      - http:
          path: user/create
          method: post

resources:
  Resources:
    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: User
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
